### ISSUE TITLE
高版本 onnxruntime 获取到的OutputName 以及 InputName 都存在不正常的情况

### ISSUE THREAD

**Issue by 0x1306a94** [hpc203/facefusion-onnxrun#1]
我在你的源码基础上添加了CMake配置 https://github.com/0x1306a94/facefusion-onnxrun/tree/add_cmake
然后我的电脑是macOS 然后通过`brew install onnxruntime`安装的版本比较高，所以打开了你注释的高版本代码
但是发现高版本的方式获取到的OutputName 以及 InputName 都存在不正常的情况

**Comment by hpc203** [comment]
我是在ubuntu系统里编写c++程序和cmake编译的，mac系统的没用过也不了解🤭。你在mac系统从onnxruntime源码编译生成动态库，这种方式的呢？

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月13日(周六) 晚上9:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [hpc203/facefusion-onnxrun] 高版本 onnxruntime 获取到的OutputName 以及 InputName 都存在不正常的情况 (Issue #1)




 
我在你的源码基础上添加了CMake配置 https://github.com/0x1306a94/facefusion-onnxrun/tree/add_cmake
 然后我的电脑是macOS 然后通过brew install onnxruntime安装的版本比较高，所以打开了你注释的高版本代码
 但是发现高版本的方式获取到的OutputName 以及 InputName 都存在不正常的情况

**Comment by 0x1306a94** [comment]
@hpc203 你是用的哪个版本的呀

**Comment by 0x1306a94** [comment]
我看官方Python 版本的 requirements.txt 中 onnxruntime=1.17.1
我用brew install onnxruntime 的版本也是 1.17.1 呢
应该是其他问题导致的，我再排查看看 @hpc203

**Comment by 0x1306a94** [comment]
@hpc203 解决问题了，使用高版本时 需要将 `GetInputNameAllocated` `GetOutputNameAllocated` 返回的智能指针同时保存，以便于延长其生命周期。 修复提交记录https://github.com/0x1306a94/facefusion-onnxrun/commit/3d4702ffdeb60b61b6fe0bfdce87def77ba38a19

**Comment by Aruen24** [comment]
> @hpc203 解决问题了，使用高版本时 需要将 `GetInputNameAllocated` `GetOutputNameAllocated` 返回的智能指针同时保存，以便于延长其生命周期。 修复提交记录[0x1306a94@3d4702f](https://github.com/0x1306a94/facefusion-onnxrun/commit/3d4702ffdeb60b61b6fe0bfdce87def77ba38a19)

./build/facefusion-onnxrun --weights ./weights/ --out ./sample_out/ --source ./images/1.jpg --target ./images/2.jpg
weights_dir: /Data2/wyw/facefusion-onnxrun-add_cmake/weights
out_dir: /Data2/wyw/facefusion-onnxrun-add_cmake/sample_out
Yolov8Face input name: images
Yolov8Face output name: output0
Face68Landmarks input name: input
Face68Landmarks ouput name: landmarks_xyscore
Face68Landmarks ouput name: heatmaps
FaceEmbdding input name: input.1
FaceEmbdding output name: 683
SwapFace input name: target
SwapFace input name: source
SwapFace output name: output
start read model_matrix.bin
Segmentation fault (core dumped)
